name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
         matrix:
          os: [windows-latest, ubuntu-18.04]

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
